AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch Application Manager EC2 instance from a custom AMI with SSM access"

Parameters:

  AmiId:
    Type: String
    Default: ami-068e657c26a322e1b
    Description: "The AMI ID to use for the EC2 instance"

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Select your EC2 KeyPair to SSH into the instance"

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
    - t3.micro
    - t2.micro
    Description: "EC2 instance type for the Application Manager"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC to launch the instance into"

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet within the VPC to launch the instance into"

  InstanceProfile:
    Type: String
    Description: "Name of an existing IAM instance profile with SSM read access"

  ExistingSecurityGroupId:
    Type: String
    Default: ""
    Description: "Optional: Provide an existing Security Group ID. Leave empty to create a new one."

Conditions:

  CreateSecurityGroup: !Equals [ !Ref ExistingSecurityGroupId, "" ]

Resources:

  ApplicationManagerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Application Manager"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8000
        ToPort: 8000
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: application-manager-sg

  ApplicationManagerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
      - !If
        - CreateSecurityGroup
        - !Ref ApplicationManagerSG
        - !Ref ExistingSecurityGroupId
      Tags:
      - Key: Name
        Value: application-manager

Outputs:

  SSHCommand:
    Description: "Example SSH command"
    Value: !Sub "ssh -i ~/.ssh/${KeyName}.pem ubuntu@${ApplicationManagerInstance.PublicIp}"

  AppURL:
    Description: Application Manager web UI (port 8000)
    Value: !Sub "http://${ApplicationManagerInstance.PublicIp}:8000"
